djangoProject1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView


urlpatterns = [
    path('', login_required(TemplateView.as_view(template_name='accueil.html'), login_url='login'), name='accueil'),
    path('admin/', admin.site.urls),
    path('', include('ppefrais.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ppefrais/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('fiches-frais/', views.fiches_frais, name='les-fiches'),
    path('fiches-frais/nouvelle-fiche/', views.FicheFraisCreate.as_view(), name='nouvelle-fiche-frais'),
    path('fiches-frais/<str:mois>/saisie-frais-hors-forfait/', views.LigneFraisHorsForfaitCreate.as_view(), name='saisie-ligne-hors-forfait'),
    path('fiches-frais/<str:mois>/edition-frais-forfaitaire/<int:pk>/', views.LigneFraisForfaitUpdate.as_view(), name='edit-ligne-forfait'),
    path('fiches-frais/<str:mois>/edition-frais-hors-forfait/<int:pk>/', views.LigneFraisHorsForfaitUpdate.as_view(), name='edit-ligne-hors-forfait'),
    path('fiches-frais/<str:mois>/suppression-frais-hors-forfait/<int:pk>/', views.LigneFraisHorsForfaitDelete.as_view(), name='suppr-ligne-hors-forfait'),
    path('fiches-frais/<str:mois>/pdf/', views.une_fiche_frais_pdf, name='une-fiche-pdf'),
    path('fiches-frais/<str:mois>/', views.une_fiche_frais, name='une-fiche'),
]

ppefrais/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from month.models import MonthField


class Visiteur(AbstractUser):
    adresse = models.CharField(max_length=30, null=True, blank=True)
    code_postal = models.CharField(max_length=5, null=True, blank=True)
    ville = models.CharField(max_length=30, null=True, blank=True)
    date_embauche = models.DateField(null=True, blank=True, default=timezone.now)

    class Meta:
        verbose_name = 'Visiteur médical'
        verbose_name_plural = 'Visiteurs médicaux'

    def __str__(self):
        return self.username


class FicheFrais(models.Model):
    class Etat(models.TextChoices):
        CLOTUREE = 'CL', _('Saisie clôturée')
        ENCOURS = 'CR', _('Fiche créée, saisie en cours')
        REMBOURSEE = 'RB', _('Remboursée')
        VALIDEE = 'VA', _('Validée et mise en paiement')

    etat = models.CharField(max_length=3, choices=Etat.choices, default=Etat.ENCOURS)
    visiteur = models.ForeignKey('Visiteur', on_delete=models.RESTRICT, default=None)
    mois = MonthField(null=False, blank=False)
    nb_justificatifs = models.PositiveIntegerField(null=True, blank=True, default=0)
    montant_valide = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=0)
    date_modif = models.DateField(null=True, default=timezone.now)

    def total_frais_forfaitaires(self):
        total = 0
        lignes_forfait = LigneFraisForfait.objects.filter(fiche_id=self.id)
        for ligne in lignes_forfait:
            total += ligne.total
        return total

    def total_frais_horsforfait(self):
        total = 0
        lignes_horsforfait = LigneFraisHorsForfait.objects.filter(fiche_id=self.id)
        for ligne in lignes_horsforfait:
            total += ligne.montant
        return total

    class Meta:
        verbose_name = 'Fiche de frais'
        verbose_name_plural = 'Fiches de frais'
        unique_together = (('mois', 'visiteur'),)

    def __str__(self):
        return str(self.mois) + ' ' + self.visiteur.__str__()

    def save(self, *args, **kwargs):
        is_new = True if not self.id else False
        super(FicheFrais, self).save(*args, **kwargs)
        if is_new:
            lff_etape = LigneFraisForfait(fiche=self, frais_forfait=LigneFraisForfait.FraisForfait.ETAPE)
            lff_fraiskm = LigneFraisForfait(fiche=self, frais_forfait=LigneFraisForfait.FraisForfait.FRAISKM)
            lff_nuithotel = LigneFraisForfait(fiche=self, frais_forfait=LigneFraisForfait.FraisForfait.NUITHOTEL)
            lff_restau = LigneFraisForfait(fiche=self, frais_forfait=LigneFraisForfait.FraisForfait.RESTAU)
            lff_etape.save()
            lff_fraiskm.save()
            lff_nuithotel.save()
            lff_restau.save()

    def get_absolute_url(self):
        return reverse('une-fiche', args=[(self.mois.strftime('%Y%m'))])


class AbstractLigneFrais(models.Model):
    fiche = models.ForeignKey('FicheFrais', on_delete=models.RESTRICT, default=None)

    def __str__(self):
        return str(self.fiche.id) + str(self.id) + '(Abstr.)'

    class Meta:
        abstract = True


class LigneFraisHorsForfait(AbstractLigneFrais):
    libelle = models.CharField(max_length=50, null=False, blank=False)
    date = models.DateField(null=False, blank=False)
    montant = models.DecimalField(decimal_places=2, max_digits=10, null=False, blank=False)

    def __str__(self):
        return str(self.fiche.id) + str(self.id) + ' (H.F.)'

    def get_absolute_url(self):
        return reverse('une-fiche', args=[(self.fiche.mois.strftime('%Y%m'))])

    class Meta:
        verbose_name = 'Ligne de frais (hors forfait)'
        verbose_name_plural = 'Lignes de frais (hors forfait)'


class LigneFraisForfait(AbstractLigneFrais):
    class FraisForfait(models.TextChoices):
        ETAPE = 'ETP', _('Forfait étape')
        FRAISKM = 'KM', _('Frais kilométrique')
        NUITHOTEL = 'NUI', _('Nuitée hôtel')
        RESTAU = 'REP', _('Repas restaurant')

    frais_forfait = models.CharField(max_length=3, choices=FraisForfait.choices, default=None)
    quantite = models.PositiveIntegerField(blank=False, null=False, default=0)

    @property
    def total(self):
        return self.montant_unitaire() * self.quantite

    def montant_unitaire(self):
        if self.frais_forfait == 'ETP':
            return 110.00
        elif self.frais_forfait == 'KM':
            return 0.62
        elif self.frais_forfait == 'NUI':
            return 80.00
        elif self.frais_forfait == 'REP':
            return 25.00
        else:
            return 0.00

    def __str__(self):
        return str(self.fiche.id) + str(self.id)

    def get_absolute_url(self):
        return reverse('une-fiche', args=[(self.fiche.mois.strftime('%Y%m'))])

    class Meta:
        verbose_name = 'Ligne de frais'
        verbose_name_plural = 'Lignes de frais'
        unique_together = (('fiche', 'frais_forfait'),)

templates/accueil.html
{% extends 'base.html' %}

{% block title %} Accueil - GSB {% endblock %}

{% block content %}

    <section class="hero is-light is-fullheight-with-navbar">
        <div class="hero-body">
            <div class="container">
                <div class="columns is-centered">
                    <div class="column" style="max-width: 376px;">
                        <div class="box has-text-centered">
                            <h2 class="subtitle">Bienvenue,
                                {% if user.get_full_name %}
                                    {{ user.get_full_name }}
                                {% else %}
                                    {{ user.username }}
                                {% endif %} !</h2>
                            <hr>
                            <p>Continuez votre visite sur notre<br>merveilleux site.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/ficheFrais.html
{% extends 'base.html' %}

{% block title %} Fiches de frais {% endblock %}

{% block content %}

    <style>

    </style>

    <section class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column" style="max-width: 720px;">
                    <div>
                        {% if ficheFrais.etat != ficheFrais.Etat.ENCOURS %}
                            <div class="level">
                                <div class="level-left">
                                    <div class="level-item">
                                        <h1 class="title is-3">
                                            Fiche de frais - {{ ficheFrais.mois|date:'F Y' }}
                                        </h1>
                                    </div>
                                    <div class="level-item">
                                        <a href="{% url 'une-fiche-pdf' ficheFrais.mois %}"
                                           class="button is-primary">
                                            <span class="icon is-small">
                                                <i class="fas fa-file-pdf"></i>
                                            </span>
                                            <span>PDF</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <h1 class="title is-3">
                                Fiche de frais - {{ ficheFrais.mois|date:'F Y' }}
                            </h1>
                        {% endif %}
                        <div class="table-container">
                            <table class="table">
                                <tr>
                                    <td>État</td>
                                    <td>{{ ficheFrais.get_etat_display }}</td>
                                </tr>
                                <tr>
                                    <td>Date de la dernière modification</td>
                                    <td>{{ ficheFrais.date_modif }}</td>
                                </tr>
                                <tr>
                                    <td>Nombre de justificatifs</td>
                                    <td>{{ ficheFrais.nb_justificatifs }}</td>
                                </tr>
                                <tr>
                                    <td>Montant validé</td>
                                    <td>{{ ficheFrais.montant_valide|floatformat:2 }} €</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <hr>

                    <div class="my-3">
                        <h2 class="title is-4">Frais forfaitaires</h2>
                        <div class="table-container">
                            <table class="table is-hoverable">
                                <thead>
                                <tr>
                                    {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                                        <th></th>{% endif %}
                                    <th>Libellé</th>
                                    <th>Quantité</th>
                                    <th>Montant unitaire</th>
                                    <th>Sous-total</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ligneFrais in lignesFraisForfait %}
                                    <tr>
                                        {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                                            <td>
                                                <div class="control">
                                                    <input type="radio"
                                                           name="lignefraisforfait"
                                                           data-url="{% url 'edit-ligne-forfait' ficheFrais.mois|date:'Ym' ligneFrais.id %}">
                                                </div>
                                            </td>{% endif %}
                                        <td>{{ ligneFrais.get_frais_forfait_display }}</td>
                                        <td class="has-text-right">{{ ligneFrais.quantite }}</td>
                                        <td class="has-text-right">
                                            {{ ligneFrais.montant_unitaire|floatformat:2 }} €
                                        </td>
                                        <td class="has-text-right">{{ ligneFrais.total|floatformat:2 }} €</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td><strong>TOTAL</strong></td>
                                    {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                                        <td></td>
                                    {% endif %}
                                    <td></td>
                                    <td></td>
                                    <td class="has-text-right has-text-weight-bold">{{ ficheFrais.total_frais_forfaitaires|floatformat:2 }}
                                        €
                                    </td>
                                </tr>
                                </tfoot>

                            </table>
                        </div>
                        {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                            <button id="lff_modifBtn"
                                    class="button is-link" disabled>
                                <span class="icon is-small">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span>Modifier la quantité</span>
                            </button>
                        {% endif %}
                    </div>

                    <hr>

                    <div class="my-3">
                        <h2 class="title is-4">Autres frais</h2>
                        <div class="table-container">
                            <table class="table is-hoverable">
                                <thead>
                                <tr>
                                    {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                                        <th></th>{% endif %}
                                    <th>Date</th>
                                    <th>Libellé</th>
                                    <th>Montant</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ligneFrais in lignesFraisHorsForfait %}
                                    <tr>
                                        {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                                            <td>
                                                <div class="control">
                                                    <input type="radio" name="lignefraishorsforfait"
                                                           data-url-edit="{% url 'edit-ligne-hors-forfait' ficheFrais.mois|date:'Ym' ligneFrais.id %}"
                                                           data-url-suppr="{% url 'suppr-ligne-hors-forfait' ficheFrais.mois|date:'Ym' ligneFrais.id %}">
                                                </div>
                                            </td>{% endif %}
                                        <td>{{ ligneFrais.date }}</td>
                                        <td>{{ ligneFrais.libelle }}</td>
                                        <td class="has-text-right">{{ ligneFrais.montant|floatformat:2 }} €</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td><strong>TOTAL</strong></td>
                                    {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                                        <td></td>
                                    {% endif %}
                                    <td></td>
                                    <td class="has-text-right has-text-weight-bold">{{ ficheFrais.total_frais_horsforfait|floatformat:2 }}
                                        €
                                    </td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
                            <p class="buttons">
                                <a href="{% url 'saisie-ligne-hors-forfait' ficheFrais.mois|date:'Ym' %}"
                                   class="button is-link">
                                <span class="icon is-small">
                                    <i class="fas fa-plus"></i>
                                </span>
                                    <span>Saisir nouvelle ligne</span>
                                </a>
                                <button id="lhf_modifBtn"
                                        class="button is-link" disabled>
                                <span class="icon is-small">
                                    <i class="fas fa-edit"></i>
                                </span>
                                    <span>Modifier</span>
                                </button>
                                <button id="lhf_supprBtn"
                                        class="button is-link" disabled>
                                <span class="icon is-small">
                                    <i class="fas fa-times"></i>
                                </span>
                                    <span>Supprimer</span>
                                </button>
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if ficheFrais.etat == ficheFrais.Etat.ENCOURS %}
        <script>
            let selected_lff_input;
            const lff_modifBtn = document.getElementById('lff_modifBtn');
            let lff_inputs = document.querySelectorAll('input[name = "lignefraisforfait"]');
            lff_inputs.forEach((input) => {
                input.addEventListener("change", function () {
                    lff_modifBtn.disabled = false;
                    selected_lff_input = input;
                });
            });

            lff_modifBtn.onclick = function () {
                location.href = selected_lff_input.getAttribute('data-url');
            };

            let selected_lhf_input;
            const lhf_modifBtn = document.getElementById("lhf_modifBtn");
            const lhf_supprBtn = document.getElementById("lhf_supprBtn");
            let lhf_inputs = document.querySelectorAll('input[name="lignefraishorsforfait"]');
            lhf_inputs.forEach((input) => {
                input.addEventListener("change", function () {
                    lhf_modifBtn.disabled = false;
                    lhf_supprBtn.disabled = false;
                    selected_lhf_input = input;
                })
            });

            lhf_modifBtn.onclick = function () {
                location.href = selected_lhf_input.getAttribute('data-url-edit');
            }

            lhf_supprBtn.onclick = function () {
                location.href = selected_lhf_input.getAttribute('data-url-suppr');
            }

        </script>
    {% endif %}


{% endblock %}

templates/ficheFraisPDF.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="fr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body {
            font-family: "Times New Roman", Times, Georgia, serif;
        }

        .text-center {
            text-align: center;
        }

        .text-justify {
            text-align: justify;
        }

        .text-right {
            text-align: right;
        }

        .text-italic {
            font-style: italic;
        }

        .dark-blue {
            color: #144485;
        }

        .light-blue {
            color: #548fc9;
        }

        .border-bottom-grey {
            border-bottom: 1px solid lightgrey;
        }

        h1 {
            font-size: 2em;
        }

        h2 {
            font-size: 1.5em;
        }

        p, span {
            font-size: 1.25em;
        }

        .pt-1 {
            padding-top: 1em;
        }

        .mb-0 {
            margin-bottom: 0;
        }

        .mb-1 {
            padding-bottom: 1em;
        }

        .mt-0 {
            margin-top: 0;
        }

        .is-marginless {
            margin: 0 0;
        }

        .underlined {
            text-decoration: underline;
        }

        #vehicules {
            margin-left: 2em;
        }

        #vehicules td {
            font-size: 1.10em;
        }

        #vehicules .vehicules-first-col {
            width: 20px;
        }

        #vehicules .vehicules-second-col {
            width: 130px;
        }

        #idfiche td {
            font-size: 1.5em;
        }

        #idfiche .idfiche-first-col {
            width: 90px;
        }

        #idfiche .idfiche-second-col {
            width: 120px;
        }

        #fraisforfaitaires, #fraishorsforfait {
            border: 0.5px solid #144485;
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            table-layout: fixed;
            border-collapse: collapse;
            font-size: 1.4em;
        }

        #fraisforfaitaires th, #fraishorsforfait th {
            padding-top: 4px;
            border: none;
        }

        #fraisforfaitaires td, #fraishorsforfait td {
            padding-top: 4px;
            vertical-align: middle;
            text-align: center;
        }

        #fraisforfaitaires .col1 {
            width: 25%;
        }

        #fraisforfaitaires .col2 {
            width: 15%;
        }

        #fraishorsforfait .col1, #fraishorsforfait .col3 {
            width: 25%;
        }

        @page {
            size: a4 portrait;

            @frame header_frame {           /* Static Frame */
                -pdf-frame-content: header_content;
                left: 50pt; right: 50pt; top: 50pt; height: 60pt;
            }
            @frame main_frame {
                -pdf-frame-content: title_content; /* Static Frame */
                left: 50pt; right: 50pt; top: 115pt; height: 435pt;
                -pdf-frame-border: 1;
            }
            @frame id_fiche_frame {
                -pdf-frame-content: idfiche_content;
                left: 70pt; right: 70pt; top: 185pt; height: 60pt;
            }
            @frame pagination_frame {
                -pdf-frame-content: pagination_content;
                width: 60pt; right: 70pt; top: 185pt; height: 60pt;
            }
            @frame fraisforfaitaires_frame {
                -pdf-frame-content: fraisforfaitaires_content;
                left: 70pt; right: 70pt; top: 250pt; height: 115pt;
            }
            @frame content_frame {          /* Content Frame */
                left: 70pt; right: 70pt; top: 370pt; height: 180pt;
            }
            @frame signature_frame {
                -pdf-frame-content: signature_content;
                left: 70pt; right: 70pt; top: 565pt; height: 30pt;
            }
            @frame footer_frame {           /* Another static Frame */
                -pdf-frame-content: footer_content;
                left: 50pt; width: 495pt; bottom: 50pt; height: 160pt;
            }
        }

        @page pages_suivantes {
            size: a4 portrait;
            @frame header_frame {           /* Static Frame */
                -pdf-frame-content: header_content;
                left: 50pt; right: 50pt; top: 50pt; height: 60pt;
            }
            @frame main_frame {
                -pdf-frame-content: title_content; /* Static Frame */
                left: 50pt; right: 50pt; top: 115pt; bottom: 140pt;
                -pdf-frame-border: 1;
            }
            @frame id_fiche_frame {
                -pdf-frame-content: idfiche_content;
                left: 70pt; right: 70pt; top: 185pt; height: 60pt;
            }
            @frame autresfraistitle_frame {
                -pdf-frame-content: autresfraistitle_content;
                left: 70pt; right: 70pt; top: 250pt; height: 20pt;
            }
            @frame pagination_frame {
                -pdf-frame-content: pagination_content;
                width: 60pt; right: 70pt; top: 185pt; height: 60pt;
            }
            @frame content_frame {          /* Content Frame */
                left: 70pt; right: 70pt; top: 270pt; bottom: 150pt;
                margin: 0pt;
            }
            @frame signature_frame {
                -pdf-frame-content: signature_content;
                left: 70pt; right: 70pt; bottom: 95pt; height: 30pt;
            }
        }

    </style>
</head>

<body>

<div id="header_content" class="text-center">
    <img src="static/img/gsb-logo.png" alt="GSB">
</div>
<div id="title_content">
    <div class="text-center">
        <h1 class="dark-blue pt-1 mb-0">ETAT DE FRAIS ENGAGES</h1>
        <h2 class="light-blue text-italic mt-0 mb-1 border-bottom-grey" style="font-family: Helvetica,sans-serif; font-size: 13px;">
            A retourner accompagné des justificatifs au plus tard le 10 du mois qui suit l'engagement des frais.
        </h2>
    </div>
</div>
<div id="idfiche_content">
    <table id="idfiche">
        <tbody>
            <tr>
                <td class="idfiche-first-col light-blue">Visiteur</td>
                <td class="idfiche-second-col text-italic">Matricule</td>
                <td class="underlined">{{ ficheFrais.visiteur.id }}</td>
            </tr>
            <tr>
                <td class="idfiche-first-col"></td>
                <td class="idfiche-second-col text-italic">Nom</td>
                <td class="underlined">{{ ficheFrais.visiteur.first_name }} {{ ficheFrais.visiteur.last_name }}</td>
            </tr>
            <tr>
                <td class="idfiche-first-col light-blue">Mois</td>
                <td class="idfiche-second-col underlined">{{ ficheFrais.mois|date:'F Y' }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>
<div id="pagination_content">
   <strong style="font-size: 1.25em">- PAGE <pdf:pagenumber> / <pdf:pagecount> -</strong>
</div>
<div id="fraisforfaitaires_content">
    <table id="fraisforfaitaires">
        <thead>
            <tr>
                <th class="dark-blue text-italic">Frais forfaitaires<sup>1</sup></th>
                <th class="dark-blue text-italic">Quantité</th>
                <th class="dark-blue text-italic">Montant unitaire<sup>2</sup></th>
                <th class="dark-blue text-italic">Total</th>
            </tr>
        </thead>
        <tbody>
        {% for ligneFrais in lignesFraisForfait %}
            <tr>
                <td class="col1">{{ ligneFrais.get_frais_forfait_display }}{% if ligneFrais.frais_forfait == 'KM' %}<sup>3</sup>{% endif %}</td>
                <td class="col2">{{ ligneFrais.quantite }}</td>
                <td class="col3">{{ ligneFrais.montant_unitaire|floatformat:2 }} €</td>
                <td class="col4">{{ ligneFrais.total|floatformat:2 }} €</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div id="signature_content">
    <h2 class="dark-blue text-italic text-right">Signature</h2>
</div>
<div id="footer_content">
    __________________________________
    <p class="is-marginless text-justify">
        <sup>1</sup> Les frais forfaitaires doivent être justifiés par une facture acquittée faisant apparaître le
        montant de la TVA.
        Ces documents ne sont pas à joindre à l’état de frais mais doivent être conservés pendant trois années.
        Ils peuvent être contrôlés par le délégué régional ou le service comptable.
    </p>
    <p class="is-marginless">
        <sup>2</sup> Tarifs en vigueur au 01/09/2010.
    </p>
    <p class="is-marginless">
        <sup>3</sup> Prix au kilomètre selon la puissance du véhicule déclaré auprès des services comptables.
    </p>
    <table id="vehicules">
        <tbody>
            <tr>
                <td class="vehicules-first-col">&bull;</td>
                <td class="vehicules-second-col">Véhicule 4CV Diesel</td>
                <td>0.52€ / Km</td>
            </tr>
            <tr>
                <td class="vehicules-first-col">&bull;</td>
                <td class="vehicules-second-col">Véhicule 5/6CV Diesel</td>
                <td>0.58€ / Km</td>
            </tr>
            <tr>
                <td class="vehicules-first-col">&bull;</td>
                <td class="vehicules-second-col">Véhicule 4CV Essence</td>
                <td>0.62€ / Km</td>
            </tr>
            <tr>
                <td class="vehicules-first-col">&bull;</td>
                <td class="vehicules-second-col">Véhicule 5/6CV Essence</td>
                <td>0.67€ / Km</td>
            </tr>
        </tbody>
    </table>
    <p class="is-marginless">
        <sup>4</sup> Tout frais « hors forfait » doit être dûment justifié par l’envoi
        d’une facture acquittée faisant apparaître le montant de TVA.
    </p>
</div>
<!-- DYNAMIC CONTENT -->
<h2 class="is-marginless text-center dark-blue text-italic">Autres frais<sup>4</sup></h2>
<table repeat="1" id="fraishorsforfait">
        <thead>
            <tr>
                <th class="dark-blue text-italic">Date</th>
                <th class="dark-blue text-italic">Libellé</th>
                <th class="dark-blue text-italic">Montant</th>
            </tr>
        </thead>
        <tbody>
        {% if lignesFraisHorsForfait.count <= 5 %}
            {% for ligneFrais in lignesFraisHorsForfait %}
                <tr>
                    <td class="col1">{{ ligneFrais.date }}</td>
                    <td class="col2">{{ ligneFrais.libelle }}</td>
                    <td class="col3">{{ ligneFrais.montant|floatformat:2 }} €</td>
                </tr>
            {% endfor %}
        {% else %}
            {% for ligneFrais in lignesFraisHorsForfait %}
                {% if forloop.counter == 6 %}<pdf:nexttemplate name="pages_suivantes"/>{% endif %}
                <tr>
                    <td class="col1">{{ ligneFrais.date }}</td>
                    <td class="col2">{{ ligneFrais.libelle }}</td>
                    <td class="col3">{{ ligneFrais.montant|floatformat:2 }} €</td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
<div id="autresfraistitle_content">
    <h2 class="is-marginless text-center dark-blue text-italic">Autres frais (suite)</h2>
</div>
</body>

</html>